CREATE TABLE transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    provider VARCHAR(50) NOT NULL,
    transaction_id VARCHAR(100) NOT NULL UNIQUE,
    meta_data JSON,
    entity_id INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    entity_payment_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    paid_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
