
-- Table: stores
CREATE TABLE IF NOT EXISTS stores (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  vendorId BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  location VARCHAR(255),
  lat DOUBLE,
  long DOUBLE,
  country VARCHAR(100),
  state VARCHAR(100),
  lga VARCHAR(100),
  landmark VARCHAR(100),
  timezone VARCHAR(100),
  postalCode VARCHAR(20),
  phone VARCHAR(20),
  email VARCHAR(100),
  bank VARCHAR(100),
  number VARCHAR(50),
  swiftCode VARCHAR(50),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table: products
CREATE TABLE IF NOT EXISTS products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table: inventories
CREATE TABLE IF NOT EXISTS inventories (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  quantity INT NOT NULL,
  unitCostPrice DECIMAL(12,2) NOT NULL,
  productId BIGINT NOT NULL,
  storeId BIGINT NOT NULL,
  arrivalOrProduceDate DATE NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (productId) REFERENCES products(id) ON DELETE CASCADE,
  FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE
);
