CREATE TABLE IF NOT EXISTS userRoles (
    userId BIGINT UNSIGNED NOT NULL,
    roleId BIGINT UNSIGNED NOT NULL,
    isActive BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT NOW(),
    updatedAt TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (userId, roleId),
    CONSTRAINT fk_userRoles_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_userRoles_role FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE
    
);



