version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=sandbox.smtp.mailtrap.io:2525
      - GF_SMTP_USER=6c53d765680ca4
      - GF_SMTP_PASSWORD=83175273732073
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_FROM_ADDRESS=hello@shop-ease.com
      - GF_SMTP_FROM_NAME=Grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
